server:
  port: 9100
  servlet:
    context-path: /api/v1/

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-administrator?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      #none, validate, update, create, and create-drop
      ddl-auto: validate
  jackson:
    default-property-inclusion: NON_NULL
    
logging:
  level:
    org.springframework: ERROR
    com.mitarcon: DEBUG  #DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
    
